import {chromium} from 'playwright';
import fs from 'fs';
const SIZE = process.env.SIZE || '720', FPS = process.env.FPS || '30', ASPECT = process.env.ASPECT || 'source', OUT = process.env.OUT || 'out.mp4';
const ctx = await chromium.launchPersistentContext('/tmp/dotfx-profile', {executablePath: '/usr/bin/google-chrome', headless: true, viewport: {width: 1400, height: 950},
  args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist', '--enable-unsafe-webgpu', '--autoplay-policy=no-user-gesture-required']});
const page = ctx.pages()[0] || await ctx.newPage();
const t0 = Date.now(); const el = () => ((Date.now() - t0) / 1000).toFixed(1) + 's';
page.on('console', m => { const t = m.text(); if (t.startsWith('[dotfx]') || m.type() === 'error') console.log(el(), m.type(), t.slice(0, 300)); });
page.on('pageerror', e => console.log(el(), 'PAGEERROR', e.message));
await page.goto('http://localhost:8765/', {waitUntil: 'load'});
await page.waitForFunction(() => window.dotfx && window.dotfx.api);
console.log(el(), 'webgpu adapter:', await page.evaluate(async () => { try { return !!(navigator.gpu && await navigator.gpu.requestAdapter()); } catch (e) { return 'err ' + e.message; } }));
await page.setInputFiles('#fVideo', 'clip2_h264.mp4');
await page.setInputFiles('#fAudio', 'song.mp3');
if (process.env.KEEP) await page.check('#keepAudio');
await page.selectOption('#bitrate', process.env.BR || '0.14'); await page.selectOption('#size', SIZE); await page.selectOption('#fps', FPS); await page.selectOption('#aspect', ASPECT);
await page.evaluate(() => window.dotfx.api.analyze(), null);
const info = await page.evaluate(() => { const S = window.dotfx; return {bpm: S.A.bpm, bars: S.A.bars.length, start: S.start, beats: S.grid.beats.length, depth: S.video.info, n: S.video.n, plan: document.getElementById('planTxt').textContent}; });
const dstat = await page.evaluate(() => { const V = window.dotfx.video; return [30, 100, 165].map(k => { const d = V.dm[Math.min(k, V.dm.length - 1)], r = [], m = []; for (let i = 0; i < d.length; i += 4) { r.push(d[i] / 255); if (d[i + 1] > 127) m.push(d[i] / 255); } r.sort((a, b) => a - b); const q = p => r[Math.floor(p * (r.length - 1))].toFixed(2); return {k, aw: V.aw, ah: V.ah, pct: [q(.05), q(.25), q(.5), q(.75), q(.95)], personD: m.length ? (m.reduce((a, b) => a + b, 0) / m.length).toFixed(2) : null, maskFrac: (m.length / r.length).toFixed(3), piv: V.piv[Math.min(k, V.piv.length - 1)]}; }); });
console.log(el(), 'DEPTHSTATS', JSON.stringify(dstat));
console.log(el(), 'ANALYSIS', JSON.stringify(info, null, 1));
await page.evaluate(() => { document.getElementById('scrub').value = 0.12; document.getElementById('scrub').dispatchEvent(new Event('input')); });
await page.waitForTimeout(1500);
await page.screenshot({path: process.env.SHOT || 'ui.png'});
const res = await page.evaluate(async () => { const r = await window.dotfx.api.doExport(); return {ext: r.ext, v: r.videoCodec, a: r.audioCodec, size: r.blob.size, sec: r.seconds, W: r.W, H: r.H}; });
console.log(el(), 'EXPORT', JSON.stringify(res));
const b64 = await page.evaluate(() => window.dotfx.api.exportBase64());
fs.writeFileSync(OUT.replace(/\.mp4$/, '.' + res.ext), Buffer.from(b64, 'base64'));
await page.screenshot({path: 'ui_after.png'});
const tc = Date.now(); await page.evaluate(() => window.dotfx.api.analyze()); console.log(el(), 'second analyze (cache) took', (Date.now() - tc) / 1000, 's');
await ctx.close();
